spring:
  application:
    name: dubbo-consumer
  dubbo:
    application:
      name: dubbo-consumer
      id: dubbo-consumer
    registry:
      address: zookeeper://192.168.0.110:2181;zookeeper://192.168.0.110:2182;zookeeper://192.168.0.110:2183