spring:
  application:
    name: dubbo-provider
  dubbo:
    application:
      name: dubbo-provider
      id: dubbo-provider
    registry:
      address: zookeeper://192.168.0.110:2181;zookeeper://192.168.0.110:2182;zookeeper://192.168.0.110:2183
    server: true
    protocol:
      name: dubbo
      port: 20880